### ISSUE TITLE
After I did npm install and ng serve, I got the error: Data path ".builders['app-shell']" should have required property 'class'

### ISSUE THREAD

**Issue by prasad-sankey** [brnrajoriya/Angular-Boilerplate#2]

**Comment by brnrajoriya** [comment]
Please check possible solutions here https://stackoverflow.com/questions/56393158/errors-data-path-buildersapp-shell-should-have-required-property-class. 

The related issue for @angular-devkit/build-angular package. Please clear cache and update this package.
